# Generated by Django 5.2.5 on 2025-09-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_is_paid_payment_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.order'),
        ),
    ]
